environment:
    matrix:
        - nodejs_version: '10'

matrix:
    fast_finish: true

build: off
shallow_clone: true

install:
    - ps: Install-Product node $env:nodejs_version
    - npm install --global npm@latest
    - set PATH=%APPDATA%\npm;%PATH%
    - npm install -g neovim
    - npm install

test_script:
    - node --version
    - npm --version
    - npm run build
    - npm run test -- --testMatch="**\src\**\*.test.ts"

cache:
    - '%APPDATA%\npm-cache'
