name: ci
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest] NOTE: windows has no nightly build now

    steps:
      - uses: actions/checkout@v2
      - uses: notomo/action-setup-nvim-lua@v1
      - run: luarocks install vusted

      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: nightly

      - name: Run tests
        env:
          VUSTED_NVIM: ${{ steps.vim.outputs.executable }}
        run: make test
