name: ci
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: notomo/action-setup-nvim-lua@dev
      - run: luarocks install busted

      - name: Checkout vusted
        uses: actions/checkout@v2
        with:
          repository: notomo/vusted
          path: vusted

      - name: Add vusted to path
        run: |
          echo "::add-path::./vusted/bin"

      - uses: rhysd/action-setup-vim@v1.2.3
        id: vim
        with:
          neovim: true
          version: nightly

      - name: Run tests
        env:
          VUSTED_NVIM: ${{ steps.vim.outputs.executable }}
        run: make test
